### PR TITLE
chore: add commit linter and release script

### PR DESCRIPTION
**Pull request by qndrey**
Automatic changelog generator with `npm run release` command

### CODE REVIEW

**Comment by fanick-ber** [comment]
Thanks, I will have to test later, once I have something to commit :-) 

Could you please perform this PR against the `develop` branch and resolve the conflicts?

**Comment by qndrey** [comment]
done.

**Comment by qndrey** [comment]
changed to develop

**Comment by fanick-ber** [comment]
@qndrey could you remove this minor merge conflict due to the other PR? You can merge afterwards.

**Pull request merged**
